// FILE: tailwind.config.js  (project root)

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,jsx}',
    './src/components/**/*.{js,jsx}',
    './src/app/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          50:      '#E9F0EC',
          100:     '#C8D9CE',
          200:     '#A4BFAF',
          300:     '#7FA48F',
          400:     '#5B896F',
          DEFAULT: '#1B4332',
          600:     '#163729',
          700:     '#122B20',
          800:     '#0D1F17',
          900:     '#09140F',
          ink:     '#000000',
        },
        gold: {
          50:      '#FFFBEB',
          100:     '#FEF3C7',
          DEFAULT: '#F59E0B',
          600:     '#D97706',
          700:     '#B45309',
          800:     '#92400E',
        },
        accent: {
          50:      '#F8EBC3',
          100:     '#F1D687',
          DEFAULT: '#D4A017',
          600:     '#B58712',
          700:     '#8C6A0F',
          800:     '#664D0B',
        },
        success: {
          50:      '#F0FDF4',
          DEFAULT: '#16A34A',
          600:     '#15803D',
          light:   '#DCFCE7',
          text:    '#14532D',
        },
        info: {
          50:      '#EFF6FF',
          DEFAULT: '#3B82F6',
          600:     '#2563EB',
          light:   '#DBEAFE',
          text:    '#1E3A8A',
        },
        warning: {
          50:      '#FFFBEB',
          DEFAULT: '#F59E0B',
          600:     '#D97706',
          light:   '#FEF3C7',
          text:    '#78350F',
        },
        danger: {
          50:      '#FFF1F2',
          DEFAULT: '#EF4444',
          600:     '#DC2626',
          light:   '#FEE2E2',
          text:    '#7F1D1D',
        },
        neutral: {
          50:  '#FAFAF9',
          100: '#F5F5F4',
          200: '#E7E5E4',
          300: '#D6D3D1',
          400: '#A8A29E',
          500: '#78716C',
          600: '#57534E',
          700: '#44403C',
          800: '#292524',
          900: '#1C1917',
        },
        // ── Semantic Theme Tokens ──
        primary:   'var(--color-text-primary)',
        secondary: 'var(--color-text-secondary)',
        muted:     'var(--color-text-muted)',
        border:    'var(--color-border)',
        surface: {
          DEFAULT: 'var(--color-surface)',
          1:       'var(--color-surface)',
          2:       'var(--color-surface-2)',
          3:       'var(--color-surface-3)',
        },
      },
      fontFamily: {
        sans:   ['var(--font-plus-jakarta)', 'system-ui', 'sans-serif'],
        arabic: ['var(--font-arabic)',       'sans-serif'],
        mono:   ['var(--font-mono)',         'monospace'],
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
        xs:    ['12px', { lineHeight: '16px' }],
        sm:    ['13px', { lineHeight: '18px' }],
        base:  ['15px', { lineHeight: '22px' }],
        md:    ['16px', { lineHeight: '24px' }],
        lg:    ['18px', { lineHeight: '26px' }],
        xl:    ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['30px', { lineHeight: '38px' }],
        '4xl': ['36px', { lineHeight: '44px' }],
        '5xl': ['48px', { lineHeight: '56px' }],
      },
      spacing: {
        '4.5': '1.125rem',
        '13':  '3.25rem',
        '15':  '3.75rem',
        '18':  '4.5rem',
        '22':  '5.5rem',
        '30':  '7.5rem',
      },
      borderRadius: {
        xs:    '4px',
        sm:    '6px',
        md:    '8px',
        lg:    '12px',
        xl:    '16px',
        '2xl': '20px',
        '3xl': '24px',
        full:  '9999px',
      },
      boxShadow: {
        xs:         '0 1px 2px 0 rgba(26,26,26,0.06)',
        sm:         '0 1px 4px 0 rgba(26,26,26,0.08)',
        md:         '0 4px 12px 0 rgba(26,26,26,0.10)',
        lg:         '0 8px 24px 0 rgba(26,26,26,0.12)',
        xl:         '0 16px 40px 0 rgba(26,26,26,0.14)',
        brand:      '0 4px 16px 0 rgba(0,0,255,0.30)',
        'brand-lg': '0 8px 28px 0 rgba(0,0,255,0.35)',
        gold:       '0 4px 14px 0 rgba(245,158,11,0.28)',
        accent:     '0 4px 14px 0 rgba(236,72,153,0.25)',
        inner:      'inset 0 1px 3px 0 rgba(26,26,26,0.08)',
      },
      animation: {
        'fade-in':     'fadeIn 0.2s ease-out both',
        'fade-up':     'fadeUp 0.3s cubic-bezier(0.16,1,0.3,1) both',
        'fade-down':   'fadeDown 0.25s cubic-bezier(0.16,1,0.3,1) both',
        'scale-in':    'scaleIn 0.2s cubic-bezier(0.16,1,0.3,1) both',
        'slide-left':  'slideLeft 0.3s cubic-bezier(0.16,1,0.3,1) both',
        'slide-right': 'slideRight 0.3s cubic-bezier(0.16,1,0.3,1) both',
        'slide-up':    'slideUp 0.3s cubic-bezier(0.16,1,0.3,1) both',
        'slide-in-left': 'slideInLeft 0.3s cubic-bezier(0.16,1,0.3,1) both',
        'bounce-sm':   'bounceSm 0.4s cubic-bezier(0.36,0.07,0.19,0.97) both',
        'wiggle':      'wiggle 0.5s ease-in-out',
        'pulse-brand': 'pulseBrand 2s cubic-bezier(0.4,0,0.6,1) infinite',
        'spin-slow':   'spin 3s linear infinite',
        'ping-slow':   'ping 2s cubic-bezier(0,0,0.2,1) infinite',
        'shimmer':     'shimmer 1.6s ease-in-out infinite',
        'pop-in':      'popIn 0.25s cubic-bezier(0.34,1.56,0.64,1) both',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        fadeDown: {
          from: { opacity: '0', transform: 'translateY(-12px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.92)' },
          to:   { opacity: '1', transform: 'scale(1)' },
        },
        slideLeft: {
          from: { opacity: '0', transform: 'translateX(20px)' },
          to:   { opacity: '1', transform: 'translateX(0)' },
        },
        slideRight: {
          from: { opacity: '0', transform: 'translateX(-20px)' },
          to:   { opacity: '1', transform: 'translateX(0)' },
        },
        // Mobile drawer slides in from the left edge
        slideInLeft: {
          from: { opacity: '0', transform: 'translateX(-100%)' },
          to:   { opacity: '1', transform: 'translateX(0)' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(100%)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        bounceSm: {
          '0%,100%': { transform: 'translateY(0)' },
          '40%':     { transform: 'translateY(-6px)' },
          '60%':     { transform: 'translateY(-3px)' },
        },
        wiggle: {
          '0%,100%': { transform: 'rotate(-3deg)' },
          '50%':     { transform: 'rotate(3deg)' },
        },
        pulseBrand: {
          '0%,100%': { opacity: '1' },
          '50%':     { opacity: '0.6' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        popIn: {
          from: { opacity: '0', transform: 'scale(0.8)' },
          to:   { opacity: '1', transform: 'scale(1)' },
        },
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34,1.56,0.64,1)',
        smooth: 'cubic-bezier(0.4,0,0.2,1)',
        snap:   'cubic-bezier(0.16,1,0.3,1)',
      },
      transitionDuration: {
        fast:   '120ms',
        normal: '200ms',
        slow:   '350ms',
      },
      zIndex: {
        base:    '0',
        raised:  '10',
        overlay: '20',
        drawer:  '30',
        modal:   '40',
        toast:   '50',
        tooltip: '60',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms')({
      strategy: 'class',
    }),
  ],
}