export const ROUTES = {
  LOGIN: '/login', REGISTER: '/register', FORGOT_PASSWORD: '/forgot-password',
  FEED: '/feed', EXPLORE: '/explore', PRODUCT: '/product',
  CART: '/cart', CHECKOUT: '/checkout', CHECKOUT_PAYMENT: '/checkout/payment',
  ORDER_CONFIRM: '/checkout/confirm', ORDERS: '/orders',
  CHAT_LIST: '/chat', CIRCLES: '/circles', WISHLIST: '/wishlist',
  PROFILE: '/profile', STOREFRONT: '/store', NOTIFICATIONS: '/notifications', SEARCH: '/search',
  VENDOR_DASHBOARD: '/vendor/dashboard', VENDOR_PRODUCTS: '/vendor/products',
  VENDOR_PRODUCT_NEW: '/vendor/products/new', VENDOR_INVENTORY: '/vendor/inventory',
  VENDOR_INVENTORY_LOGS: '/vendor/inventory/history', VENDOR_IMPORT: '/vendor/import',
  VENDOR_VIDEOS: '/vendor/videos', VENDOR_VIDEO_UPLOAD: '/vendor/videos/upload',
  VENDOR_CIRCLES: '/vendor/circles', VENDOR_CHAT: '/vendor/chat',
  VENDOR_ANALYTICS: '/vendor/analytics', VENDOR_ORDERS: '/vendor/orders',
  VENDOR_SETTINGS: '/vendor/settings',
}
